# Generated by Django 3.2.17 on 2023-02-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_beer_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='desc',
            field=models.TextField(default='Description'),
        ),
    ]
